version: '2'
services:
  apache2:
    image: registry.byperiscope.com/docker/apache
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes_from:
      - php-fpm:ro
    links:
      - php-fpm
  php-fpm:
    build:
      context: php-fpm
      args:
        DRUPAL_VERSION: 8.4.3
    restart: on-failure
    volumes:
      - www:/var/www/html
      - private:/var/www/private
      - ./www/config:/var/www/html/sites/config
      - ./www/modules/custom:/var/www/html/modules/custom
      - ./www/profiles:/var/www/html/profiles
      - ./www/themes/custom:/var/www/html/themes/custom
  mysql:
    image: mariadb
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=root
volumes:
  www:
    driver: local
  private:
    driver: local
  mysql:
    driver: local
