version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
volumes:
  mysql: {}
