version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: on-failure
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql:
